### ISSUE TITLE
The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/))

### ISSUE THREAD

**Issue by Quentinb** [DigDes/SoapCore#14]
Hi All,

Thanks for your efforts in putting this together. Trying it on a sample project have have run into the above error message. From my searching it appears that "BasicHttpBinding" is related to Soap 1.1 and wsBasicHttpBinding is for SOAP 1.2. By the looks of it, using System.ServiceModel does not support the ws binding.

The error happens at:
`var requestMessage = _messageEncoder.ReadMessage(httpContext.Request.Body, 0x10000, httpContext.Request.ContentType);`
in SoapEndpointMiddleware.cs

**Comment by Quentinb** [comment]
Using wsBinding is not required, but in my case, I have no control over the data sent to the server. Using the below should be enough to cause the error. I get the error using Fiddler and SoapUI for testing.

The NS - http://www.w3.org/2003/05/soap-envelope is for Soap 1.2

`<S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope">
	<S:Header>
		...
  </S:Header>
  <S:Body>
    ...
	</S:Body>
</S:Envelope>`

**Comment by matafonoff** [comment]
I get the same error.

Steps to reproduce (the esiest way):
- Open VS2017
- Create aspnet core project 
- Install SoapCore
- Create a simple SOAP service
- Run project
- Open VS2017
- Create test project (or console, does not matter)
- Try to add service reference to running aspnet core project. 

At first VS2017 tries SOAP 1.2, it failes.
Then VS2017 uses SOAP 1.1 and everything works.

**Comment by Quentinb** [comment]
In my case I was talking to a 3rd party service and am not able to influence the SOAP versions used. I ended up rolling my own SOAP handler in .Net.

**Comment by MickeyFinn** [comment]
To Add some color into this issue as I've seen  that it doesn't seem to support custom binding.
Code Example:
// create Soap 1.2 Binding
TextMessageEncodingBindingElement textBindingElement = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressing10, System.Text.Encoding.UTF8);
 HttpTransportBindingElement httpBindingElement = new HttpTransportBindingElement();
 httpBindingElement.AllowCookies = true;
 httpBindingElement.MaxBufferSize = int.MaxValue;
 httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
 CustomBinding soap12Binding = new CustomBinding(textBindingElement, httpBindingElement);
 // service
 app.UseSoapEndpoint<SoapService>("/SoapService.svc", soap12Binding);


Now call that service from a client and the stack trace is...
Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HLBJT99U8TBU", Request id "0HLBJT99U8TBU:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: This message cannot support the operation because it has been read.
at System.ServiceModel.Channels.Message.EnsureReadMessageState()
at System.ServiceModel.Channels.Message.GetReaderAtBodyContents()
at SoapCore.SoapEndpointMiddleware.GetRequestArguments(Message requestMessage, OperationDescription operation, Dictionary`2& outArgs)
at SoapCore.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by itn3000** [comment]
I think it is because  `MessageEncoder.GetReaderAtBodyContents` was called twice when soap12 request come(soap12 does not have `SOAPAction` header).
https://github.com/DigDes/SoapCore/blob/78bc953419fc7bda5080a635bc021295d9a60d9f/src/SoapCore/SoapEndpointMiddleware.cs#L95
https://github.com/DigDes/SoapCore/blob/78bc953419fc7bda5080a635bc021295d9a60d9f/src/SoapCore/SoapEndpointMiddleware.cs#L167

**Comment by itn3000** [comment]
It might be fixed on #65, #71

**Comment by argiegonzales** [comment]
Is this already fixed?... i still get this error

**Comment by VasTheGreek** [comment]
> 
> 
> Is this already fixed?... i still get this error

Same here. Anyone knows if this has been addressed yet?

**Comment by kotovaleksandr** [comment]
> 
> 
> > Is this already fixed?... i still get this error
> 
> Same here. Anyone knows if this has been addressed yet?

@VasTheGreek @argiegonzales Attach your service and model for reproduce error

**Comment by ansongoldade** [comment]
I am able to reproduce with the following
```
var encodingOptions = new[]
{
  new SoapEncoderOptions
  {
    MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap11), WriteEncoding = Encoding.UTF8,
    ReaderQuotas = new XmlDictionaryReaderQuotas()
  },
  new SoapEncoderOptions
  {
    MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12), WriteEncoding = Encoding.UTF8,
    ReaderQuotas = new XmlDictionaryReaderQuotas()
  }
};

app.UseSoapEndPoint(typeOf(MyService), "MyService.asmx", encodingOptions, SoapSerializer.XmlSerializer);
```

Sending a SOAP 1.1 message with `Content-Type: text/xml` and `SOAPAction: http://tempuri.org/TheMethod` headers results in success. Here is the 1.1 message.
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <TheMethod xmlns="http://tempuri.org/">
    </TheMethod>
  </soap:Body>
</soap:Envelope>
```

Sending an SOAP 1.2 message to the server with `Content-Type: application/soap+xml` header results is the error referenced in this issue. Here is the 1.2 message.
```
<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <TheMethod xmlns="http://tempuri.org/">
    </TheMethod>
  </soap12:Body>
</soap12:Envelope>
```

**Comment by richarddavenport** [comment]
I'm actually getting this with having a property as a nullable DateTimeOffset:
`public System.DateTimeOffset? InServiceDate { get; set; }`

For example, in the sample project you can change the return type in the interface and implementation:

```
[ServiceContract]
public interface ISampleService
{
	[OperationContract]
	Task<System.DateTimeOffset?> AsyncMethod();
}

public class SampleService : ISampleService
{
	public Task<DateTimeOffset?> AsyncMethod()
	{
		return Task.Run(() => (DateTimeOffset?) null);
	}
}
```

Then I get this error:
```
System.ServiceModel.CommunicationException: The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages. (Parameter 'reader')
 ---> System.ArgumentException: The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages. (Parameter 'reader')
   --- End of inner exception stack trace ---
```

**Comment by lexon0011** [comment]
I have the same issue. I also use the content-type `application/soap+xml`
Any solution for this problem?

**Comment by lexon0011** [comment]
I solved it with the following statement in the `startup.cs`:
```
TextMessageEncodingBindingElement textBindingElement = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressingAugust2004, System.Text.Encoding.UTF8);
HttpTransportBindingElement httpBindingElement = new HttpTransportBindingElement();
CustomBinding soap12Binding = new CustomBinding(textBindingElement, httpBindingElement);

app.UseSoapEndpoint<INotificationService>("/MyService.asmx", soap12Binding, SoapSerializer.XmlSerializer);
```

**Comment by mtinwala** [comment]
> 
> 
> I solved it with the following statement in the `startup.cs`:
> 
> ```
> TextMessageEncodingBindingElement textBindingElement = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressingAugust2004, System.Text.Encoding.UTF8);
> HttpTransportBindingElement httpBindingElement = new HttpTransportBindingElement();
> CustomBinding soap12Binding = new CustomBinding(textBindingElement, httpBindingElement);
> 
> app.UseSoapEndpoint<INotificationService>("/MyService.asmx", soap12Binding, SoapSerializer.XmlSerializer);
> ```

I implemented this kind of binding and now I am getting a different error.

crit: SoapCore.SoapEndpointMiddleware[0]
      An error occurred when trying to service a request on SOAP endpoint: /myendpoint.asmx
System.InvalidOperationException: The body of the message cannot be read because it is empty.
   at System.ServiceModel.Channels.Message.GetReaderAtBodyContents()
   at SoapCore.SoapEndpointMiddleware.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)

**Comment by the-black-wolf** [comment]
I can confirm the bug is still there, but you have to explicitly specify `SoapSerializer.XmlSerializer`, otherwise it does not error out (it does produce a different wsdl though)

**Comment by sudarshan-jhawar** [comment]
I manage to solve this issue by changing _SoapSerializer_.
 I changed `SoapSerializer.XmlSerializer` to `SoapSerializer.DataContractSerializer` 

e.g. 
`app.UseSoapEndpoint<IFileUploadService>("/FileUploadService.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);`
