### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [DigDes/SoapCore#23]
Hi,

please improve error messages. Currently, some errors are not handled properly causing an unhandled exception!

Best regards,
Markus Hartmair

Code
```cs
[ServiceContract(Name = "MyService.asmx")]
public interface IMyService
{
    int SomeMethod(int arg1, out MyModel arg2);
}

public class MyModel
{
    public string MyProperty { get; internal set; } /* Should be public setter */
}
```

(expected) Exception:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot deserialize type 'MyModel' because it contains property 'MyProperty' which has no public setter.
  Source=System.Xml
  StackTrace:
   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, ArrayList list)
   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping structMapping)
   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, Dictionary`2 memberInfos)
   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(StructMapping structMapping)
   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod(TypeMapping mapping)
   at System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods()
   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(String[] methods, XmlMapping[] xmlMappings, Type[] types)
   at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at SoapCore1.ServiceBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer) in ServiceBodyWriter.cs:line 52
```

Unhandled server exception!
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=cubido.Common.AspNetCore.Soap
  StackTrace:
   at SoapCore1.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext() in SoapEndpointMiddleware.cs:line 129
```
Possible fix working for me:
`SoapEndpointMiddleware:ProcessOperation:126`
```cs
catch (Exception exception)
{
    // Create response message
    /* InnerstException */
    while (exception.InnerException != null)
        exception = exception.InnerException;
    var errorText = exception/*.InnerException*/.Message;
    var transformer = serviceProvider.GetService<ExceptionTransformer>();
    if (transformer != null)
        errorText = transformer.Transform(exception/*.InnerException*/);
    var bodyWriter = new FaultBodyWriter(new Fault { FaultString = errorText });
    ...
}
```

**Comment by kotovaleksandr** [comment]
Hi! Fixed in https://github.com/DigDes/SoapCore/pull/30
Check new version on nuget: https://www.nuget.org/packages/SoapCore/0.9.2

**Comment by cubidobusinesssolutions** [comment]
Hi, 

@kotovaleksandr This didn't fix it for me; now the exception is 

```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=No parameterless constructor defined for this object.
  Source=mscorlib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SoapCore1.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext() in SoapEndpointMiddleware.cs:line 97
```

Best regards

**Comment by kotovaleksandr** [comment]
Please, check latest version of sources.

**Comment by cubidobusinesssolutions** [comment]
Hi, 

@kotovaleksandr error message is now shown in client, thanks.

Best regards
Markus
